### ISSUE TITLE
Can fdm send mail?

### ISSUE THREAD

**Issue by dave-kennedy** [nicm/fdm#11]
I noticed in the manual "An action may be defined to pass mail on over SMTP." Does this mean fdm can be used to send mail? How would I use the following action?

    action "mysmtpaction" smtp server "smtp.server"

**Comment by nicm** [comment]
Hi

It can deliver mail it has fetched to an SMTP server, you can use it the
same way you would use any other action.

**Comment by dave-kennedy** [comment]
I must not understand the use case for this. Here's what I tried:

```
account "test" stdin

match account "test" action smtp server "my.smtp.server"
    from "me@somewhere"
```

Then invoking fdm with:

```sh
$ cat message.txt
To: someguy@whatever
cc:
Fcc: +outbox
Subject: Test
--------
This is a test.

$ cat message.txt | fdm -a test fetch
```

It eventually just timed out.

**Comment by nicm** [comment]
Show me the -vvvv log.

**Comment by dave-kennedy** [comment]
```txt
version is: fdm 1.7, started at: Sun May 15 10:39:03 2016
running on: Linux 4.4.6-gentoo #1 SMP Thu Apr 28 00:17:29 MDT 2016 x86_64
host is: gentoo localhost ::1
home is: /home/dave
loading configuration from /home/dave/.fdm.conf
added account "test": fetch=stdin
added rule 0: matches=account "test" lambda=0:smtp server "smtp-mail.outlook.com" port smtp to "(null)" 
configuration loaded
locking using: flock 
options are: verify-certificates, maximum-size=134217728, timeout=900, default-user="dave", command-user="dave", file-umask=077, queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: started, pid is 17289
parent: 0 children, 0 dead children
parent: child 17290 (test) started
test: fetch started, pid 17290
test: user is 1000
test: started processing
test: fetching
test: fetch loop start
test: calling fetch state (0x413080, flags 0x02)
test: fetch, again
test: fetch loop start
test: calling fetch state (0x412ea0, flags 0x02)
< To: someguy@whatever
Subject: Test
--------
This is a test.

test: fetch, mail
test: bad date header, using current time
test: found 5 lines, 0 in body
test: message-id not found
test: couldn't add received header
test: found 0 wrapped lines
test: got message 1: size 70, body 70
test: fetch loop start
test: trying (match) message 1
test: tried account "test", result now 1
test: finished rule 0, result 1
test: matched to rule 0
test: action <rule 0>:0 (smtp), user dave
test: match message 1, deliver
test: trying (deliver) message 1
test: message 1, running action <rule 0>:0 (smtp) as user dave
test: sending action to parent
test: deliver message 1, blocked
test: calling fetch state (0x412e80, flags 0x00)
test: fetch, exit
test: queued 1; blocked 1; flags 0x00
test: polling: 1, timeout=900000
parent: got message type 0, id 1 from child 17290
parent: deliver child 17291 started (uid 1000)
parent: 2 children, 0 dead children
test: deliver started, pid 17291
test: deliver user is: dave (1000/1000), home is: /home/dave
test: connect: Connection timed out
parent: got message type 2, id 0 from child 17291
test: fetch loop start
parent: sending exit message to child 17291
test: got message type 2, id 1
test: trying (deliver) message 1
parent: 2 children, 0 dead children
test: deliver message 1, error
test: fetching error. aborted
test: 0 messages processed in 127.333 seconds
test: finished processing. exiting
test: sending exit message to parent
test: waiting for exit message from parent
parent: got message type 1, id 0 from child 17290
parent: sending exit message to child 17290
parent: waiting for children
parent: child 17291 returned 0
parent: waiting for children
parent: 1 children, 1 dead children
parent: 1 children, 1 dead children
parent: child 17290 socket error
parent: 1 children, 1 dead children
parent: waiting for children
parent: child 17290 returned 1
parent: waiting for children
parent: waiting for children
parent: finished, total time 127.334 seconds
```

I don't really expect this to work because Outlook wants my full email address for my username, which is not specified anywhere. But your insistence that it should work reminded me that it uses port 587. After specifying that in the config, I got this error instead:

```txt
version is: fdm 1.7, started at: Sun May 15 10:53:37 2016
running on: Linux 4.4.6-gentoo #1 SMP Thu Apr 28 00:17:29 MDT 2016 x86_64
host is: gentoo localhost ::1
home is: /home/dave
loading configuration from /home/dave/.fdm.conf
added account "test": fetch=stdin
added rule 0: matches=account "test" lambda=0:smtp server "smtp-mail.outlook.com" port 587 to "(null)" 
configuration loaded
locking using: flock 
options are: verify-certificates, maximum-size=134217728, timeout=900, default-user="dave", command-user="dave", file-umask=077, queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: started, pid is 17591
parent: 0 children, 0 dead children
parent: child 17592 (test) started
test: fetch started, pid 17592
test: user is 1000
test: started processing
test: fetching
test: fetch loop start
test: calling fetch state (0x413080, flags 0x02)
test: fetch, again
test: fetch loop start
test: calling fetch state (0x412ea0, flags 0x02)
< To: someguy@whatever
Subject: Test
--------
This is a test.

test: fetch, mail
test: bad date header, using current time
test: found 5 lines, 0 in body
test: message-id not found
test: couldn't add received header
test: found 0 wrapped lines
test: got message 1: size 70, body 70
test: fetch loop start
test: trying (match) message 1
test: tried account "test", result now 1
test: finished rule 0, result 1
test: matched to rule 0
test: action <rule 0>:0 (smtp), user dave
test: match message 1, deliver
test: trying (deliver) message 1
test: message 1, running action <rule 0>:0 (smtp) as user dave
test: sending action to parent
test: deliver message 1, blocked
test: calling fetch state (0x412e80, flags 0x00)
test: fetch, exit
test: queued 1; blocked 1; flags 0x00
test: polling: 1, timeout=900000
parent: got message type 0, id 1 from child 17592
parent: deliver child 17593 started (uid 1000)
parent: 2 children, 0 dead children
test: deliver started, pid 17593
test: deliver user is: dave (1000/1000), home is: /home/dave
< 220 BLU436-SMTP162.smtp.hotmail.com Microsoft ESMTP MAIL Service, Version: 8.0.9200.16384 ready at  Sun, 15 May 2016 09:54:14 -0700 
> HELO localhost
< 250 BLU436-SMTP162.smtp.hotmail.com Hello [184.96.132.136]
> MAIL FROM:<me@somewhere>
< 530 5.7.0 Must issue a STARTTLS command first
test: unexpected response: 530 5.7.0 Must issue a STARTTLS command first
> QUIT
parent: got message type 2, id 0 from child 17593
test: fetch loop start
parent: sending exit message to child 17593
test: got message type 2, id 1
test: trying (deliver) message 1
parent: 2 children, 0 dead children
test: deliver message 1, error
test: fetching error. aborted
test: 0 messages processed in 0.439 seconds
test: finished processing. exiting
test: sending exit message to parent
test: waiting for exit message from parent
parent: got message type 1, id 0 from child 17592
parent: sending exit message to child 17592
parent: waiting for children
parent: child 17593 returned 0
parent: waiting for children
parent: 1 children, 1 dead children
parent: 1 children, 1 dead children
parent: child 17592 socket error
parent: 1 children, 1 dead children
parent: waiting for children
parent: child 17592 returned 1
parent: waiting for children
parent: waiting for children
parent: finished, total time 0.439 seconds
```

fdm yells at me when I try adding `starttls` anywhere in the action.

**Comment by nicm** [comment]
Are you sure it is listening on port 25? Many mail servers have moved to
port 587.

version is: fdm 1.7, started at: Sun May 15 10:39:03 2016
running on: Linux 4.4.6-gentoo #1 SMP Thu Apr 28 00:17:29 MDT 2016 x86_64
host is: gentoo localhost ::1
home is: /home/dave
loading configuration from /home/dave/.fdm.conf
added account "test": fetch=stdin
added rule 0: matches=account "test" lambda=0:smtp server
"smtp-mail.outlook.com" port smtp to "(null)"
configuration loaded
locking using: flock
options are: verify-certificates, maximum-size=134217728, timeout=900,
default-user="dave", command-user="dave", file-umask=077,
queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: started, pid is 17289
parent: 0 children, 0 dead children
parent: child 17290 (test) started
test: fetch started, pid 17290
test: user is 1000
test: started processing
test: fetching
test: fetch loop start
test: calling fetch state (0x413080, flags 0x02)
test: fetch, again
test: fetch loop start
test: calling fetch state (0x412ea0, flags 0x02)
< To: someguy@whatever
Subject: Test
--------
This is a test.

test: fetch, mail
test: bad date header, using current time
test: found 5 lines, 0 in body
test: message-id not found
test: couldn't add received header
test: found 0 wrapped lines
test: got message 1: size 70, body 70
test: fetch loop start
test: trying (match) message 1
test: tried account "test", result now 1
test: finished rule 0, result 1
test: matched to rule 0
test: action <rule 0>:0 (smtp), user dave
test: match message 1, deliver
test: trying (deliver) message 1
test: message 1, running action <rule 0>:0 (smtp) as user dave
test: sending action to parent
test: deliver message 1, blocked
test: calling fetch state (0x412e80, flags 0x00)
test: fetch, exit
test: queued 1; blocked 1; flags 0x00
test: polling: 1, timeout=900000
parent: got message type 0, id 1 from child 17290
parent: deliver child 17291 started (uid 1000)
parent: 2 children, 0 dead children
test: deliver started, pid 17291
test: deliver user is: dave (1000/1000), home is: /home/dave
test: connect: Connection timed out
parent: got message type 2, id 0 from child 17291
test: fetch loop start
parent: sending exit message to child 17291
test: got message type 2, id 1
test: trying (deliver) message 1
parent: 2 children, 0 dead children
test: deliver message 1, error
test: fetching error. aborted
test: 0 messages processed in 127.333 seconds
test: finished processing. exiting
test: sending exit message to parent
test: waiting for exit message from parent
parent: got message type 1, id 0 from child 17290
parent: sending exit message to child 17290
parent: waiting for children
parent: child 17291 returned 0
parent: waiting for children
parent: 1 children, 1 dead children
parent: 1 children, 1 dead children
parent: child 17290 socket error
parent: 1 children, 1 dead children
parent: waiting for children
parent: child 17290 returned 1
parent: waiting for children
parent: waiting for children
parent: finished, total time 127.334 seconds

I don't really expect this to work because Outlook wants my full email
address for my username, which is not specified anywhere. But your
insistence that it should work reminded me that it uses port 587. After
specifying that in the config, I got this error instead:

version is: fdm 1.7, started at: Sun May 15 10:53:37 2016
running on: Linux 4.4.6-gentoo #1 SMP Thu Apr 28 00:17:29 MDT 2016 x86_64
host is: gentoo localhost ::1
home is: /home/dave
loading configuration from /home/dave/.fdm.conf
added account "test": fetch=stdin
added rule 0: matches=account "test" lambda=0:smtp server
"smtp-mail.outlook.com" port 587 to "(null)"
configuration loaded
locking using: flock
options are: verify-certificates, maximum-size=134217728, timeout=900,
default-user="dave", command-user="dave", file-umask=077,
queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: started, pid is 17591
parent: 0 children, 0 dead children
parent: child 17592 (test) started
test: fetch started, pid 17592
test: user is 1000
test: started processing
test: fetching
test: fetch loop start
test: calling fetch state (0x413080, flags 0x02)
test: fetch, again
test: fetch loop start
test: calling fetch state (0x412ea0, flags 0x02)
< To: someguy@whatever
Subject: Test
--------
This is a test.

test: fetch, mail
test: bad date header, using current time
test: found 5 lines, 0 in body
test: message-id not found
test: couldn't add received header
test: found 0 wrapped lines
test: got message 1: size 70, body 70
test: fetch loop start
test: trying (match) message 1
test: tried account "test", result now 1
test: finished rule 0, result 1
test: matched to rule 0
test: action <rule 0>:0 (smtp), user dave
test: match message 1, deliver
test: trying (deliver) message 1
test: message 1, running action <rule 0>:0 (smtp) as user dave
test: sending action to parent
test: deliver message 1, blocked
test: calling fetch state (0x412e80, flags 0x00)
test: fetch, exit
test: queued 1; blocked 1; flags 0x00
test: polling: 1, timeout=900000
parent: got message type 0, id 1 from child 17592
parent: deliver child 17593 started (uid 1000)
parent: 2 children, 0 dead children
test: deliver started, pid 17593
test: deliver user is: dave (1000/1000), home is: /home/dave
< 220 BLU436-SMTP162.smtp.hotmail.com Microsoft ESMTP MAIL Service,
Version: 8.0.9200.16384 ready at  Sun, 15 May 2016 09:54:14 -0700
> HELO localhost
< 250 BLU436-SMTP162.smtp.hotmail.com Hello [184.96.132.136]
> MAIL FROM:<me@somewhere>
< 530 5.7.0 Must issue a STARTTLS command first
test: unexpected response: 530 5.7.0 Must issue a STARTTLS command first
> QUIT
parent: got message type 2, id 0 from child 17593
test: fetch loop start
parent: sending exit message to child 17593
test: got message type 2, id 1
test: trying (deliver) message 1
parent: 2 children, 0 dead children
test: deliver message 1, error
test: fetching error. aborted
test: 0 messages processed in 0.439 seconds
test: finished processing. exiting
test: sending exit message to parent
test: waiting for exit message from parent
parent: got message type 1, id 0 from child 17592
parent: sending exit message to child 17592
parent: waiting for children
parent: child 17593 returned 0
parent: waiting for children
parent: 1 children, 1 dead children
parent: 1 children, 1 dead children
parent: child 17592 socket error
parent: 1 children, 1 dead children
parent: waiting for children
parent: child 17592 returned 1
parent: waiting for children
parent: waiting for children
parent: finished, total time 0.439 seconds

fdm yells at me when I try adding starttls anywhere in the action.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/nicm/fdm/issues/11#issuecomment-219297170>

**Comment by dave-kennedy** [comment]
Well, no, it's listening on port 587 apparently. But after I change the port I get the TLS error in my previous reply.

**Comment by nicm** [comment]
I don't remember if fdm supports SMTPS and I'm pretty sure it doesn't
support STARTTLS, sounds like you need one of them.

**Comment by dave-kennedy** [comment]
That's what I needed to know. Thanks!
