### ISSUE TITLE
exchange online vs. POP3

### ISSUE THREAD

**Issue by szrobag2020** [nicm/fdm#123]
Is it possible to fetch mails on exchange online? As i read the basic POP3 connection is disabled. 
I got  unexpected data: -ERR Logon failure: unknown user name or bad password. error however no credentials were changed.

**Comment by iamleot** [comment]
Hello!

I don't think that's an `fdm` issue but more Exchange Online that probably no longer permit to use basic authentication. (At least to an account I had access it seems that it's the case since January 20 2023).

I think that there are two possible ways to solve that:

* if you are using 2FA I think it can be possible to set "application password" and then use them for basic authentication (but actually probably also depend on the account, e.g. for account I had access it doesn't seem it is the case (but maybe you are/can talk with the admin(s))
* `xoauth2` support should be added to `pop3`

(Probably most of the logic can be steal from `imap`!)

**Comment by szrobag2020** [comment]
Hello,
Yes, sorry, the program is great! MS had a change about basic auth few days ago. I am lookig for 2FA possibilities...
