### ISSUE TITLE
Can't login to imap server

### ISSUE THREAD

**Issue by qingyunha** [nicm/fdm#30]
```bash
$ fdm -k  -vv  fetch 
version is: fdm 1.7, started at: Sat Jan  7 11:13:42 2017
running on: Linux 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64
host is: Inspiron localhost 127.0.0.1
home is: /home/taoqy
loading configuration from /home/taoqy/.fdm.conf
added action "inbox": deliver=0:mbox "%h/mail/INBOX" 
added account "xx@xx": fetch=imaps server "imap.exmail.qq.com" port 993 user "xx@xx" folders "INBOX"
added rule 0: matches=all actions="inbox"
configuration loaded
locking using: flock 
options are: keep-all, verify-certificates, maximum-size=33554432, timeout=900, default-user="taoqy", command-user="taoqy", file-umask=077, queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: 3 file descriptors in use
parent: started, pid is 25677
parent: 0 children, 0 dead children
parent: child 25678 (xx@xx) started
xx@xx: 4 file descriptors in use
xx@xx: fetch started, pid 25678
xx@xx: user is 1000
xx@xx: started processing
xx@xx: fetching
xx@xx: unexpected data: 2 BAD ȱ��login��������
xx@xx: fetching error. aborted
xx@xx: 0 messages processed in 5.117 seconds
xx@xx: polled for 0.261 seconds (0.000 blocked)
xx@xx: finished processing. exiting
parent: sending exit message to child 25678
parent: 1 children, 0 dead children
xx@xx: 4 file descriptors in use
parent: 1 children, 0 dead children
parent: child 25678 socket error
parent: 1 children, 0 dead children
parent: child 25678 returned 1
parent: finished, total time 5.118 seconds
parent: 3 file descriptors in use
host is: Inspiron localhost 127.0.0.1
home is: /home/taoqy
loading configuration from /home/taoqy/.fdm.conf
added action "inbox": deliver=0:mbox "%h/mail/INBOX" 
added account "xx@xx": fetch=imaps server "imap.exmail.qq.com" port 993 user "xx@xx" folders "INBOX"
added rule 0: matches=all actions="inbox"
configuration loaded
locking using: flock 
options are: keep-all, verify-certificates, maximum-size=33554432, timeout=900, default-user="taoqy", command-user="taoqy", file-umask=077, queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: 3 file descriptors in use
parent: started, pid is 25677
parent: 0 children, 0 dead children
parent: child 25678 (xx@xx) started
xx@xx: 4 file descriptors in use
xx@xx: fetch started, pid 25678
xx@xx: user is 1000
xx@xx: started processing
xx@xx: fetching
xx@xx: unexpected data: 2 BAD ȱ��login��������
xx@xx: fetching error. aborted
xx@xx: 0 messages processed in 5.117 seconds
xx@xx: polled for 0.261 seconds (0.000 blocked)
xx@xx: finished processing. exiting
parent: sending exit message to child 25678
parent: 1 children, 0 dead children
xx@xx: 4 file descriptors in use
parent: 1 children, 0 dead children
parent: child 25678 socket error
parent: 1 children, 0 dead children
parent: child 25678 returned 1
parent: finished, total time 5.118 seconds
parent: 3 file descriptors in use
```

And successfully do this in python
```python
import imaplib
mail = imaplib.IMAP4_SSL("imap.exmail.qq.com", 993)
mail.login("xx@xx", "passwd")
print mail.list()
```

**Comment by nicm** [comment]
Please show log with -vvvv.



On 7 Jan 2017 3:32 am, "qingyunha" <notifications@github.com> wrote:

$ fdm -k  -vv  fetch
version is: fdm 1.7, started at: Sat Jan  7 11:13:42 2017
running on: Linux 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32
UTC 2016 x86_64
host is: Inspiron localhost 127.0.0.1
home is: /home/taoqy
loading configuration from /home/taoqy/.fdm.conf
added action "inbox": deliver=0:mbox "%h/mail/INBOX"
added account "xx@xx": fetch=imaps server "imap.exmail.qq.com" port
993 user "xx@xx" folders "INBOX"
added rule 0: matches=all actions="inbox"
configuration loaded
locking using: flock
options are: keep-all, verify-certificates, maximum-size=33554432,
timeout=900, default-user="taoqy", command-user="taoqy",
file-umask=077, queue-high=2, queue-low=1,
strip-characters="\<>$%^&*|{}[]"'`;"using tmp directory: /tmpparent: 3
file descriptors in useparent: started, pid is 25677parent: 0
children, 0 dead childrenparent: child 25678 (xx@xx) startedxx@xx: 4
file descriptors in usexx@xx: fetch started, pid 25678xx@xx: user is
1000xx@xx: started processingxx@xx: fetchingxx@xx: unexpected data: 2
BAD ȱ��login��������xx@xx: fetching error. abortedxx@xx: 0 messages
processed in 5.117 secondsxx@xx: polled for 0.261 seconds (0.000
blocked)xx@xx: finished processing. exitingparent: sending exit
message to child 25678parent: 1 children, 0 dead childrenxx@xx: 4 file
descriptors in useparent: 1 children, 0 dead childrenparent: child
25678 socket errorparent: 1 children, 0 dead childrenparent: child
25678 returned 1parent: finished, total time 5.118 secondsparent: 3
file descriptors in usehost is: Inspiron localhost 127.0.0.1home is:
/home/taoqyloading configuration from /home/taoqy/.fdm.confadded
action "inbox": deliver=0:mbox "%h/mail/INBOX" added account "xx@xx":
fetch=imaps server "imap.exmail.qq.com" port 993 user "xx@xx" folders
"INBOX"added rule 0: matches=all actions="inbox"configuration
loadedlocking using: flock options are: keep-all, verify-certificates,
maximum-size=33554432, timeout=900, default-user="taoqy",
command-user="taoqy", file-umask=077, queue-high=2, queue-low=1,
strip-characters="\<>$%^&*|{}[]"'`;"using tmp directory: /tmpparent: 3
file descriptors in useparent: started, pid is 25677parent: 0
children, 0 dead childrenparent: child 25678 (xx@xx) startedxx@xx: 4
file descriptors in usexx@xx: fetch started, pid 25678xx@xx: user is
1000xx@xx: started processingxx@xx: fetchingxx@xx: unexpected data: 2
BAD ȱ��login��������xx@xx: fetching error. abortedxx@xx: 0 messages
processed in 5.117 secondsxx@xx: polled for 0.261 seconds (0.000
blocked)xx@xx: finished processing. exitingparent: sending exit
message to child 25678parent: 1 children, 0 dead childrenxx@xx: 4 file
descriptors in useparent: 1 children, 0 dead childrenparent: child
25678 socket errorparent: 1 children, 0 dead childrenparent: child
25678 returned 1parent: finished, total time 5.118 secondsparent: 3
file descriptors in use

And successfully do this in python

import imaplib
mail = imaplib.IMAP4_SSL("imap.exmail.qq.com", 993)
mail.login("xx@xx", "passwd")print mail.list()

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nicm/fdm/issues/30>, or mute the thread

**Comment by qingyunha** [comment]
```sh
$ fdm -k -vvvv fetch
version is: fdm 1.7, started at: Sat Jan  7 17:33:32 2017
running on: Linux 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64
host is: Inspiron localhost 127.0.0.1
home is: /home/taoqy
loading configuration from /home/taoqy/.fdm.conf
added action "inbox": deliver=0:mbox "%h/mail/INBOX" 
added account "xx@xx": fetch=imaps server "imap.exmail.qq.com" port 993 user "xx@xx" folders "INBOX"
added rule 0: matches=all actions="inbox"
configuration loaded
locking using: flock 
options are: keep-all, verify-certificates, maximum-size=33554432, timeout=900, default-user="taoqy", command-user="taoqy", file-umask=077, queue-high=2, queue-low=1, strip-characters="\<>$%^&*|{}[]"'`;"
using tmp directory: /tmp
parent: 3 file descriptors in use
parent: started, pid is 28161
parent: 0 children, 0 dead children
parent: child 28162 (xx@xx) started
xx@xx: 4 file descriptors in use
xx@xx: fetch started, pid 28162
xx@xx: user is 1000
xx@xx: started processing
xx@xx: fetching
xx@xx: fetch loop start
xx@xx: calling fetch state (0x416390, flags 0x02)
xx@xx: fetch, again
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41af80, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
< * OK [CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE ID UIDPLUS AUTH=LOGIN NAMESPACE] QQMail IMAP4Server ready
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41b620, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
> 1 CAPABILITY
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41b710, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
< * CAPABILITY IMAP4 IMAP4rev1 IDLE XAPPLEPUSHSERVICE AUTH=LOGIN NAMESPACE CHILDREN ID UIDPLUS
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41b710, flags 0x02)
xx@xx: fetch, again
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41bab0, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
< 1 OK CAPABILITY Completed
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41bab0, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
> 2 LOGIN {23}
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41b840, flags 0x02)
xx@xx: fetch, block
xx@xx: queued 0; blocked 0; flags 0x02
xx@xx: polling: 2, timeout=900000
< 2 BAD ȱ��login��������
xx@xx: fetch loop start
xx@xx: calling fetch state (0x41b840, flags 0x02)
xx@xx: unexpected data: 2 BAD ȱ��login��������
xx@xx: fetch, error
xx@xx: fetching error. aborted
xx@xx: 0 messages processed in 3.231 seconds
xx@xx: polled for 0.226 seconds (0.000 blocked)
xx@xx: finished processing. exiting
xx@xx: sending exit message to parent
xx@xx: waiting for exit message from parent
parent: got message type 1, id 0 from child 28162
parent: sending exit message to child 28162
parent: 1 children, 0 dead children
xx@xx: 4 file descriptors in use
xx@xx: 28162: allocated=34043, freed=34043, difference=0, peak=33928
xx@xx: 28162: mallocs=17, reallocs=0, frees=17
xx@xx: 28162: 0 unfreed blocks
parent: 1 children, 0 dead children
parent: child 28162 socket error
parent: 1 children, 0 dead children
parent: waiting for children
parent: child 28162 returned 1
parent: waiting for children
parent: waiting for children
parent: finished, total time 3.233 seconds
parent: 3 file descriptors in use
parent: 28161: allocated=53431, freed=53431, difference=0, peak=34545
parent: 28161: mallocs=61, reallocs=2, frees=61
parent: 28161: 0 unfreed blocks
```

**Comment by nicm** [comment]
Looks to me like the server doesn't support strings as literals at least
for LOGIN, this is a requirement for IMAP and a server bug. fdm uses these
kind of strings extensively so they need to be supported.

**Comment by qingyunha** [comment]
Thank you. Is this mean that the server does not implement the protocol strictly？

**Comment by nicm** [comment]
Right it does not implement the protocol properly, this is a requirement
(look at section 4.3 of RFC3501).


On 7 Jan 2017 10:29 am, "qingyunha" <notifications@github.com> wrote:

Thank you. Is this mean that the server does not implement the protocol
strictly？

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nicm/fdm/issues/30#issuecomment-271075500>, or mute the
thread
