### ISSUE TITLE
^(To|Cc|Bcc):(.*,){20,}.*$: regexec failed

### ISSUE THREAD

**Issue by Siltaar** [nicm/fdm#36]
Hi,

I'm working on another "spam" detection, trying to eliminate emails with more than 20 recipients using the following rule:
`match "^(To|Cc|Bcc):(.*,){20,}.*$" in headers action maildir "%h/.Maildir/.spam"`

For non-compliant messages it's ok, but a compliant message reports the error in subject of this message.

I tried the regexp with grep, it's not getting the message because all recipients are not trully in one line, or, if I try to get only one recipient it works, but I never get an error this way.

It remembers me that too long regexps (for instance : From: user@domain|user@domain… ) must sometimes be split in smaller ones. Here I try to match big things, it might be related…

**Comment by nicm** [comment]
fdm just matches on the text as it is, if the headers are split across
multiple lines that is what you need to match. You could write a script and
use a rewrite rule to fix up these headers first.

**Comment by Siltaar** [comment]
No multiline regexp available from FDM ?

**Comment by nicm** [comment]
It uses REG_NEWLINE so . doesn't match newline and ^$ do. You could try
explicitly including \n in the .* bit.


On 25 Mar 2017 10:48 am, "Simon Descarpentries" <notifications@github.com>
wrote:

No multiline regexp available from FDM ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nicm/fdm/issues/36#issuecomment-289204099>, or mute the
thread

**Comment by Siltaar** [comment]
Well, I tried \n and \\n with no success.

**Comment by Siltaar** [comment]
I also tried `[\n\r]+` with no more success.
