### ISSUE TITLE
Encrypted password.

### ISSUE THREAD

**Issue by lebarondemerde** [nicm/fdm#44]
Hi.

Is it possible to store the account password encrypted, or make pass run gpg to decrypt and get password from a file?

For instance, with isync it is possible to use something like this:

``PassCmd "gpg2 -q --for-your-eyes-only --no-tty -d ~/somefile.gpg"``

Thanks.

**Comment by tmiasko** [comment]
You can use command substitution for that, for example:
```
pass   $(gpg --quiet --decrypt ~/.password.gpg)
```

**Comment by lebarondemerde** [comment]
Oh.
Thanks!

**Comment by wu0lss4j** [comment]
> You can use command substitution for that, for example:
> 
> ```
> pass   $(gpg --quiet --decrypt ~/.password.gpg)
> ```

Perhaps do you know if instead of requesting the encrypted pass via gpg, passwordstore (https://www.passwordstore.org/) could be used?

this is my `.fdm.conf`

```
# ~/.fdm.conf
# Catch-all action (maildir):
set no-received

# exec $(pass isync/gmail)

action "inbox" maildir "%h/Gmail-fdm/INBOX"

account "gmail"
imaps server "imap.gmail.com" port 993
user "myemail@gmail.com"
pass $(eval pass isync/gmail)
folders {"INBOX" "to_archive" "moneytrail"}

# Match all mail and deliver using the 'inbox' action.
match all action "inbox"
```

in my scenario, it will exit code 2, expecting the master password to return the gmail password, however, if before running the `fdm -kv fetch` I run `pass isync/gmail` type the master password and then run `fdm -kv fetch`, then and only then, fdm will connect to gmail and fetch and deliver mails

Any ideas?
